name: Ejercicio 10 - Desempeño y Recursos

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start timer
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: System info BEFORE
        run: |
          echo "=== RECURSOS INICIALES ==="
          echo "CPU cores:"
          nproc

          echo "CPU Model:"
          lscpu | grep "Model name"

          echo ""
          echo "Memoria:"
          free -h

          echo ""
          echo "Disco:"
          df -h

          echo ""
          echo "Procesos activos:"
          ps aux | wc -l

      - name: Heavy operation
        run: |
          echo "Simulando operación pesada..."
          npm install || true
          npm test || true

      - name: System info AFTER
        if: always()
        run: |
          echo "=== RECURSOS DESPUÉS ==="
          echo "Memoria:"
          free -h

          echo ""
          echo "Disco:"
          df -h

          echo ""
          echo "Procesos activos:"
          ps aux | wc -l

      - name: End timer and calculate duration
        if: always()
        run: |
          END_TIME=$(date +%s)
          echo "Duración total del job: $((END_TIME - START_TIME)) segundos"
