name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      os:
        required: false
        type: string
        default: ubuntu-latest

    outputs:
      test-result:
        description: "Result of the tests"
        value: ${{ jobs.test.outputs.result }}

jobs:
  test:
    runs-on: ${{ inputs.os }}

    outputs:
      result: ${{ steps.test.outcome }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        id: test
        run: npm test
