name: Use Reusable Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  call-test:
    uses: ./.github/workflows/reusable-test.yml
    with:
      node-version: '18'
      os: 'ubuntu-latest'
